apiVersion: v1
kind: ReplicationController
metadata:
  name: bbox-client
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: sodaclient
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        app: sodaclient
        io.contiv.tenant: bevco
        io.contiv.network: bevco-net1
        io.contiv.net-group: sodaapp
    spec:
      containers:
      - name: bboxservice
        image: contiv/nc-busybox
        command:
          - sleep
          - "7200"

