apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-srv
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: sugar-server
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        app: sugar-server
        io.contiv.tenant: bevco
        io.contiv.network: bevco-net1
        io.contiv.net-group: sugardb
    spec:
      containers:
      - name: redis-tcpdump
        image: jainvipin/redis
        ports:
        - containerPort: 6379

